# Was noch nicht funkitoniert: Anlegen (mit success) und danach den State direkt wieder auslesen
# Vermutung: Wahrscheinlich muss die Statemachine released werden!!

###


POST http://localhost:8080/order/success
Content-Type: application/json

{
  "customer": "ABC Racing",
  "articleNumber": 2421,
  "count": 1
}

###

POST http://localhost:8080/order/fail
Content-Type: application/json

{
	"customer": "ABC Racing",
	"articleNumber": 2421,
	"count": 1
}

###

GET http://localhost:8080/retry/fail/4d458fd0-3c80-46a7-b2d5-23393ac25dff


###

GET http://localhost:8080/retry/success/4d458fd0-3c80-46a7-b2d5-23393ac25dff

###
GET http://localhost:8080/order/15070217-c6d0-11eb-ab72-e21d4b4d3494

###
GET http://localhost:8080/order/transitions/1fe24899-c6d1-11eb-9053-e21d4b4d3494

###
# for ((i=1;i<=2000;i++)); do curl -s -X POST --location "http://localhost:8080/order/success" -H "Content-Type: application/json" -d "{\"customer\": \"ABC Racing\", \"articleNumber\": 2421, \"count\": 1}" > /dev/null; done



